services:

  vetsoft-app:
    image: vetsoft-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - TIME_ZONE=True


