# Generated by Django 5.0.4 on 2024-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medicine_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='Address not provided', max_length=100),
            preserve_default=False,
        ),
    ]
