name: cd

on:
    release:
        types: [published]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get the date
              run: echo "date=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vetsoft:latest,${{ secrets.DOCKER_HUB_USERNAME }}/vetsoft:${{ env.date }}

            - name: Deploy in Render
              run: curl ${{ secrets.RENDER_HOOK }}